### ISSUE TITLE
Support Request for deleting all the events in time span

### ISSUE THREAD

**Issue by Moorocks** [eCrimeLabs/MISP-PurgeEvents#4]
Let's assume that I want to delete all the attributes within the last 30 days from the present date.
Would it be possible to delete the events with your code?

Also I would like to know that this script is not working as expected.

I gave the first date as 2010-01-01 and last date as 2023-09-09 and did not give any org id in config.py file. With these dates all the events should be deleted.
However lot of events are not being purged.

Let me know what needs to be done in this case?
<img width="2029" alt="Screenshot 2023-09-16 at 1 26 35 pm" src="https://github.com/eCrimeLabs/MISP-PurgeEvents/assets/143619572/cd2d1774-8184-40c6-970c-a65b5a58f558">

**Comment by eCrimeLabs** [comment]
Hey @Moorocks 

Q: Delete all the attributes within the last 30 days from the present date
A: Yes it is for sure you need to define the 30 days based on date, and I typically set the present data for tomorrow :) Also remember the dates is based on when the event were created on your server and NOT the event date some times added to the event itself :)

```
$ venv/bin/python misp-purgeevents.py -f 2023-08-17 -l 2023-09-18 -v
```


Q: I gave the first date as 2010-01-01 and last date as 2023-09-09 and did not give any org id in config.py file. With these dates all the events should be deleted. However lot of events are not being purged.
A: This can be due to you not removed the "exclude_orgs" and set this to:
```
exclude_orgs = [
]
```

If you still have issue i would need a bit more information on how you config file is and what command line you used, and what output the program gave :)

Also a little background if you have not seen it 
https://www.ecrimelabs.com/blog/2022/6/29/misp-purge-events-tool

**Comment by Moorocks** [comment]
Hi @eCrimeLabs ,

Ah now I get it.
The exclude orgs is not removed from the script. 
I fixed the script and it is now working. 
I will upload the script below, so somecan use this if they do not want to exclude any org id's.
